name: Comment

on:
  issues:
    types: [opened, edited]

jobs:
  comment-id:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Run script
      uses: ultimatemediaorg/CoolShortener-action@v1.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
