name: Comment

on: [issues]

jobs:
  comment-id:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Run script
      uses: ultimatemediaorg/CoolShortener-action@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
